config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to: 'login#login'
  post '/login', to: 'login#create'
  delete '/logout', to: 'login#destroy'
  get '/login/main'
  root to: 'users#index'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user

private

def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def main
    end
    def login
    end
  
    def create
      @user = User.find_by(uid: session_params[:uid])
  
      if @user&.authenticate(session_params[:password])
        session[:user_id] = @user.id
        redirect_to login_main_url, notice: 'ログイン完了です!'
      else
        render :login
      end
    end
  
    def destroy
      reset_session
      redirect_to root_url, notice: 'ログアウトしました、さようなら...'
    end
  
    private
    def session_params
      params.require(:session).permit(:uid, :password)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
      end
    
      def new
        @user = User.new
      end
    
      def create
        @user = User.new(user_params)
    
        if @user.save
          redirect_to new_user_path, notice: "ユーザーを登録しました!"
        else
          render :new
        end
      end
    
      private
    
      def user_params
        params.require(:user).permit(:uid, :password)
      end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to 'ユーザー登録', new_user_path , class: 'nav-link' %></li>
        <% if current_user %>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, class: 'nav-link'%></li>
        <% else %>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link'%></li>
        <% end %>
      </ul>
    </header>
    <%= yield %>
  </body>
</html>

app/views/login/login.html.erb
<h1>ログイン</h1>

<%= form_with scope: :session, local:  true do |f|%>
  <div class="form-group">
  <%= f.label :uid, 'ユーザーID' %>
  <%= f.text_field :uid, class: 'form-control', id: 'session_uid'%></div>
  <div class="form-group">
  <%= f.label :password, 'パスワード' %>
  <%= f.password_field :password, class: 'form-control', id: 'session_password'%></div>
  <%= f.submit 'ログインする', class: 'btn btn-primary'%>
<% end %>

app/views/login/main.html.erb
<h1>ログイン成功、おめでとうな</h1>

<div class="nav-item">
  <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, url:  {action: :create} do |f| %>
  <div class="form-group">
    <%= f.label :uid, 'ユーザーID'%>
    <%= f.text_field :uid, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード'%>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit '登録する', class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>ログインしてください</h1>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<%= render partial: 'form', locals: { user: @user} %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>